// List all tickets
GET http://localhost:8080/tickets/

###
// Create a new ticket
POST http://localhost:8080/tickets/
Content-Type: application/x-www-form-urlencoded

subject = JobRunr is not working &
description = I have a JobNotFoundException

> {% client.global.set("ticket_id", response.body.id); %}

###
// View the new ticket
GET http://localhost:8080/tickets/{{ticket_id}}

###
// Resolve the new ticket
POST http://localhost:8080/tickets/{{ticket_id}}/resolve
Content-Type: application/x-www-form-urlencoded

resolution = If you have a JobNotFoundException, it means you changed the signature of your job and it cannot be found anymore in your code.