SELECT VECTOR_EMBEDDING(ALL_MINILM_L12_V2 USING 'I have an exception' as DATA) AS embedding;

UPDATE TICKETS
	SET EMBEDDING = (SELECT VECTOR_EMBEDDING(ALL_MINILM_L12_V2 USING 'I have a JobNotFoundException' AS DATA) AS EMB FROM DUAL)
	WHERE ID = HEXTORAW('9982638671f641d185edf3fedd11c2f7');