services:
  oracle-ai:
    image: gvenzl/oracle-free:23.7-faststart
    container_name: oracle-ai
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: sys_user_password
      APP_USER: TEST
      APP_USER_PASSWORD: TEST
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
    volumes:
      - ./src/main/resources/model:/data/mining/model
      - ./src/main/resources/container-entrypoint-initdb.d:/container-entrypoint-initdb.d
    restart: unless-stopped