ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE TABLE TEST.TICKETS
(
	ID          RAW(16) PRIMARY KEY,
	VERSION     NUMBER(10),
	SUBJECT     VARCHAR2(200) NOT NULL,
	DESCRIPTION CLOB,
	CREATED_AT  TIMESTAMP(6) NOT NULL,
	RESOLUTION  CLOB,
	STATUS      VARCHAR2(10),
	EMBEDDING   VECTOR
);

PROMPT '✓ Table TICKETS was created successfully.'