ALTER SESSION SET CONTAINER=FREEPDB1;

GRANT SELECT ON v_$session TO "TEST";
GRANT SELECT ON v_$sql_plan_statistics_all TO "TEST";
GRANT SELECT ON v_$sql_plan TO "TEST";
GRANT SELECT ON v_$sql TO "TEST";
GRANT SELECT on V_$SESSION to "TEST";
GRANT DB_DEVELOPER_ROLE TO "TEST";
GRANT CREATE MINING MODEL TO "TEST";

CREATE OR REPLACE DIRECTORY DM_DUMP as '/data/mining/model';
GRANT READ, WRITE ON DIRECTORY DM_DUMP TO "TEST";
GRANT EXECUTE ON DBMS_VECTOR TO TEST;

CONNECT TEST/TEST@FREEPDB1;
EXEC DBMS_VECTOR.DROP_ONNX_MODEL(model_name => 'ALL_MINILM_L12_V2', force => true);
PROMPT 'Loading ALL_MINILM_L12_V2 ONNX model...'
EXEC DBMS_VECTOR.LOAD_ONNX_MODEL(directory => 'DM_DUMP', file_name => 'all_MiniLM_L12_v2.onnx', model_name => 'ALL_MINILM_L12_V2');
PROMPT '✓ Loaded ALL_MINILM_L12_V2 ONNX model successfully.'